apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-service
  template:
    metadata:
      labels:
        app: blog-service
    spec:
      containers:
      - name: blog-service
        image: sriyaamperayani/blog_service:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  selector:
    app: blog-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
